In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

df = pd.read_csv('energydata_complete.csv')
df.head()

date  Appliances  lights     T1       RH_1    T2       RH_2  \
0  2016-01-11 17:00:00          60      30  19.89  47.596667  19.2  44.790000   
1  2016-01-11 17:10:00          60      30  19.89  46.693333  19.2  44.722500   
2  2016-01-11 17:20:00          50      30  19.89  46.300000  19.2  44.626667   
3  2016-01-11 17:30:00          50      40  19.89  46.066667  19.2  44.590000   
4  2016-01-11 17:40:00          60      40  19.89  46.333333  19.2  44.530000   

      T3       RH_3         T4  ...         T9   RH_9     T_out  Press_mm_hg  \
0  19.79  44.730000  19.000000  ...  17.033333  45.53  6.600000        733.5   
1  19.79  44.790000  19.000000  ...  17.066667  45.56  6.483333        733.6   
2  19.79  44.933333  18.926667  ...  17.000000  45.50  6.366667        733.7   
3  19.79  45.000000  18.890000  ...  17.000000  45.40  6.250000        733.8   
4  19.79  45.000000  18.890000  ...  17.000000  45.40  6.133333        733.9   

   RH_out  Windspeed  Visibility  Tdewpoint        rv1        rv2  
0    92.0   7.000000   63.000000        5.3  13.275433  13.275433  
1    92.0   6.666667   59.166667        5.2  18.606195  18.606195  
2    92.0   6.333333   55.333333        5.1  28.642668  28.642668  
3    92.0   6.000000   51.500000        5.0  45.410389  45.410389  
4    92.0   5.666667   47.666667        4.9  10.084097  10.084097  

[5 rows x 29 columns]

In [2]:
df.isna().sum()

date           0
Appliances     0
lights         0
T1             0
RH_1           0
T2             0
RH_2           0
T3             0
RH_3           0
T4             0
RH_4           0
T5             0
RH_5           0
T6             0
RH_6           0
T7             0
RH_7           0
T8             0
RH_8           0
T9             0
RH_9           0
T_out          0
Press_mm_hg    0
RH_out         0
Windspeed      0
Visibility     0
Tdewpoint      0
rv1            0
rv2            0
dtype: int64

In [3]:
df.duplicated().sum()

np.int64(0)

In [4]:
df.describe(
)

Appliances        lights            T1          RH_1            T2  \
count  19735.000000  19735.000000  19735.000000  19735.000000  19735.000000   
mean      97.694958      3.801875     21.686571     40.259739     20.341219   
std      102.524891      7.935988      1.606066      3.979299      2.192974   
min       10.000000      0.000000     16.790000     27.023333     16.100000   
25%       50.000000      0.000000     20.760000     37.333333     18.790000   
50%       60.000000      0.000000     21.600000     39.656667     20.000000   
75%      100.000000      0.000000     22.600000     43.066667     21.500000   
max     1080.000000     70.000000     26.260000     63.360000     29.856667   

               RH_2            T3          RH_3            T4          RH_4  \
count  19735.000000  19735.000000  19735.000000  19735.000000  19735.000000   
mean      40.420420     22.267611     39.242500     20.855335     39.026904   
std        4.069813      2.006111      3.254576      2.042884      4.341321   
min       20.463333     17.200000     28.766667     15.100000     27.660000   
25%       37.900000     20.790000     36.900000     19.530000     35.530000   
50%       40.500000     22.100000     38.530000     20.666667     38.400000   
75%       43.260000     23.290000     41.760000     22.100000     42.156667   
max       56.026667     29.236000     50.163333     26.200000     51.090000   

       ...            T9          RH_9         T_out   Press_mm_hg  \
count  ...  19735.000000  19735.000000  19735.000000  19735.000000   
mean   ...     19.485828     41.552401      7.411665    755.522602   
std    ...      2.014712      4.151497      5.317409      7.399441   
min    ...     14.890000     29.166667     -5.000000    729.300000   
25%    ...     18.000000     38.500000      3.666667    750.933333   
50%    ...     19.390000     40.900000      6.916667    756.100000   
75%    ...     20.600000     44.338095     10.408333    760.933333   
max    ...     24.500000     53.326667     26.100000    772.300000   

             RH_out     Windspeed    Visibility     Tdewpoint           rv1  \
count  19735.000000  19735.000000  19735.000000  19735.000000  19735.000000   
mean      79.750418      4.039752     38.330834      3.760707     24.988033   
std       14.901088      2.451221     11.794719      4.194648     14.496634   
min       24.000000      0.000000      1.000000     -6.600000      0.005322   
25%       70.333333      2.000000     29.000000      0.900000     12.497889   
50%       83.666667      3.666667     40.000000      3.433333     24.897653   
75%       91.666667      5.500000     40.000000      6.566667     37.583769   
max      100.000000     14.000000     66.000000     15.500000     49.996530   

                rv2  
count  19735.000000  
mean      24.988033  
std       14.496634  
min        0.005322  
25%       12.497889  
50%       24.897653  
75%       37.583769  
max       49.996530  

[8 rows x 28 columns]

In [5]:
#quiz number 17

X = df[['T2']]
y = df['T6']

lr = LinearRegression()
lr.fit(X, y)

LinearRegression()

In [6]:
y_pred = lr.predict(X)
print(y_pred)
rmse = np.sqrt(mean_squared_error(y, y_pred))

print(f"{rmse:.3f}")

[ 5.37165597  5.37165597  5.37165597 ... 19.67562202 19.19818742
 18.86506395]
3.644


In [21]:
#quiz number 18
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_error

df = df.drop(columns=["date", "lights"], errors='ignore')

X = df.drop(columns=["Appliances"])
y = df["Appliances"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [10]:
X_train_scaled
X_test_scaled

array([[0.43294615, 0.27554825, 0.12066877, ..., 0.3       , 0.51234794,
        0.51234794],
       [0.53854277, 0.85778509, 0.37727163, ..., 0.35454545, 0.46937859,
        0.46937859],
       [0.48574446, 0.27883772, 0.11146111, ..., 0.19090909, 0.00259746,
        0.00259746],
       ...,
       [0.43681802, 0.40712719, 0.18899927, ..., 0.51742424, 0.79266914,
        0.79266914],
       [0.55015839, 0.46732456, 0.33438333, ..., 0.52272727, 0.60824256,
        0.60824256],
       [0.43294615, 0.50219298, 0.21322995, ..., 0.74393939, 0.19877963,
        0.19877963]])

In [11]:
lr = LinearRegression()
lr.fit(X_train_scaled, y_train)

LinearRegression()

In [16]:
y_train_pred = lr.predict(X_train_scaled)
y_train_pred

array([ 49.97775425, 100.31632974,  40.12912536, ...,  59.47229745,
       103.23225103,  88.1415215 ])

In [18]:
mae_train = mean_absolute_error(y_train, y_train_pred)
print(f"{mae_train:.3f}")

53.742


In [22]:
#quiz number 19
rmse_train = np.sqrt(mean_squared_error(y_train, y_train_pred))

print(f"{rmse_train:.3f}")

95.216


In [23]:
#quiz number 20
y_test_pred = lr.predict(X_test_scaled)
mae_test = mean_absolute_error(y_test, y_test_pred)

print(f"{mae_test:.3f}")

53.643


In [24]:
#quiz number 21
rmse_test = np.sqrt(mean_squared_error(y_test, y_test_pred))

print(f"{rmse_test:.3f}")

93.640


In [ ]:
#quiz number 22

# From the previous output:
# MAE on the training set = 53.742
# RMSE on the training set = 95.216
# MAE on the testing set = 53.643
# RMSE on the testing set = 93.640

# Therefore, No overfitting

In [29]:
#quiz number 23

from sklearn.linear_model import Ridge

ridge_model = Ridge()
ridge_model.fit(X_train_scaled, y_train)

y_test_pred_ridge = ridge_model.predict(X_test_scaled)

rmse_test_ridge = np.sqrt(mean_squared_error(y_test, y_test_pred_ridge))

print(f"{rmse_test_ridge:.3f}")
print('yes, there is change')

93.709
yes, there is change


In [35]:
#quiz number 24

from sklearn.linear_model import Lasso

lasso_model = Lasso()
lasso_model.fit(X_train_scaled, y_train)


Lasso()

In [40]:
X_train.columns

Index(['T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3', 'T4', 'RH_4', 'T5', 'RH_5',
       'T6', 'RH_6', 'T7', 'RH_7', 'T8', 'RH_8', 'T9', 'RH_9', 'T_out',
       'Press_mm_hg', 'RH_out', 'Windspeed', 'Visibility', 'Tdewpoint', 'rv1',
       'rv2'],
      dtype='object')

In [38]:
lasso_model.coef_

array([  0.        ,  56.94451601,   0.        ,  -0.        ,
         0.        ,   0.        ,  -0.        ,   0.        ,
        -0.        ,   0.        ,   0.        ,  -0.        ,
        -0.        ,  -0.        ,   0.        , -26.10288797,
        -0.        ,  -0.        ,   0.        ,  -0.        ,
       -50.29397595,   5.14314792,   0.        ,  -0.        ,
        -0.        ,  -0.        ])

In [42]:
feature_weights = pd.DataFrame({'Feature': X_train.columns, 'Weight': lasso_model.coef_})
feature_weights

Feature     Weight
0            T1   0.000000
1          RH_1  56.944516
2            T2   0.000000
3          RH_2  -0.000000
4            T3   0.000000
5          RH_3   0.000000
6            T4  -0.000000
7          RH_4   0.000000
8            T5  -0.000000
9          RH_5   0.000000
10           T6   0.000000
11         RH_6  -0.000000
12           T7  -0.000000
13         RH_7  -0.000000
14           T8   0.000000
15         RH_8 -26.102888
16           T9  -0.000000
17         RH_9  -0.000000
18        T_out   0.000000
19  Press_mm_hg  -0.000000
20       RH_out -50.293976
21    Windspeed   5.143148
22   Visibility   0.000000
23    Tdewpoint  -0.000000
24          rv1  -0.000000
25          rv2  -0.000000

In [45]:
print('4 non-zero feature weights')

4 non-zero feature weights


In [46]:
#quiz number 25

y_test_pred_lasso = lasso_model.predict(X_test_scaled)

rmse_test_lasso = np.sqrt(mean_squared_error(y_test, y_test_pred_lasso))

print(f"{rmse_test_lasso:.3f}")

99.424
